### ISSUE TITLE
How can i install Lucifer ML after dowloading all files ?? 

### ISSUE THREAD

**Issue by takfarine** [d4rk-lucif3r/LuciferML#11]
im trying to install Lucifer ML in my computer  **without  using internet** , and it doesn't seems to work for me

i  tried this !pip install ../input/lucifer-ml/lucifer-ml-0.0.79/setup.py

**Comment by d4rk-lucif3r** [comment]
Please use this https://stackoverflow.com/questions/12324601/how-to-install-a-python-module-via-its-setup-py-in-windows

**Comment by takfarine** [comment]
@d4rk-lucif3r 
![Screenshot from 2022-02-14 18-47-26](https://user-images.githubusercontent.com/87461007/153959718-7359225d-4c69-4539-94d5-f3fa6727c953.png)
